sudo: required
services: 
  - docker

before_install:
  - docker build -t krystynakruchkovska/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true krystynakruchkovska/docker-react npm run test